In [53]:
## Python Package Imports
import numpy as np
import pandas as pd
import pickle

## Custom Module Imports
from activation_functions.SoftMax import SoftMax
from activation_functions.ReLU import ReLU

In [44]:

class nn_layer:
    """
    Represents a weight matrix (rows, cols) = (num_neurons, input_size)
    num_neurons is the number of neurons we wish to put in this layer
    input_size is the fixed value defined by the last layer's outputs

    The relationship between input size and number of neurons for multiple layers is ---
    input_size = num_neurons_prev
    input_size_next/output_size = num_neurons
    ... etc
    """
    def __init__(self, input_size, num_neurons, activ_func):
        # self.weight_matrix = np.array([np.random.rand(input_size) for _ in range(num_neurons)])
        # Above line has been upgraded to line below
        self.weight_matrix = np.random.randn(num_neurons, input_size)
        self.bias_vector = np.random.rand(num_neurons)
        self.activation_func = activ_func

    def batch_input(self, input_matrix):
        """
        Returns the matrix product [input_matrix] * [weight_matrix]^T of dimensions
        (num_inputs, input_size) * (input_size, num_neurons) = (num_inputs, num_neurons)
        Where the output columns of the matrix are the output of the i^{th} layer of neurons


        (num_inputs, num_neurons) + (num_neurons) is X + bias, where the bias is added row-wise (to each row/data instance)
        """
        raw_batch_output = np.dot(input_matrix, self.weight_matrix.T) + self.bias_vector
        batch_output = self.activation_func.forward(raw_batch_output)
        return batch_output
    

class simple_neural_network:
    """
    Represents a neural network as an array of 'nn_layer' objects
    """
    def __init__(self, input_size):
        self.nn_array = []
        self.input_size = input_size


    def add_layer(self, num_neurons, activ_func):
        """
        New layer must have input size corresponding to previous layer's output size
        num_neurons - is the number of neurons in the current layer
        activ_func - is the activation function that should be applied to the outputs of this layer
        """
        if(len(self.nn_array) == 0):
            self.nn_array.append(nn_layer(self.input_size, num_neurons, activ_func))
        else:
            prev_output_size = self.nn_array[-1].weight_matrix.shape[0]
            self.nn_array.append(nn_layer(
                input_size = prev_output_size, 
                num_neurons = num_neurons, 
                activ_func=activ_func))


    def describe_network(self):
        # weight matrix shape is (num_neurons, input_size)
        for layer in self.nn_array:
            print(layer)

    def forward_pass(self, input_matrix):
        for i in range(len(self.nn_array)):
            layer = self.nn_array[i]
            input_matrix = layer.batch_input(input_matrix)    
        return input_matrix

In [49]:
faux_data_matrix =  np.random.randn(10, 5)
nn = simple_neural_network(5)
nn.add_layer(5, ReLU())
nn.add_layer(6, SoftMax())
out_mat = nn.forward_pass(faux_data_matrix)

In [50]:
out_mat

array([[7.84732253e-03, 1.84399280e-03, 1.73772053e-04, 7.68598010e-02,
        2.58853662e-04, 9.13016258e-01],
       [4.63540745e-01, 1.65779837e-01, 1.76792450e-01, 1.73129511e-04,
        3.16088113e-02, 1.62105027e-01],
       [1.15426763e-04, 7.02030611e-03, 1.00520534e-03, 4.20149355e-01,
        5.51771388e-03, 5.66191993e-01],
       [1.85154268e-01, 7.10233744e-04, 1.17191502e-03, 1.02023122e-01,
        4.66327062e-04, 7.10474135e-01],
       [5.05482165e-01, 9.51734683e-02, 2.45448503e-01, 1.45520171e-03,
        4.70641107e-02, 1.05376551e-01],
       [2.99494652e-01, 1.82709447e-01, 2.36512918e-01, 7.84448563e-03,
        1.07335271e-01, 1.66103227e-01],
       [5.54970602e-03, 4.40722319e-04, 4.73001142e-04, 8.23329595e-01,
        7.49987656e-04, 1.69456988e-01],
       [1.37724842e-06, 2.43585709e-08, 3.47128345e-09, 8.46065498e-01,
        1.41505131e-08, 1.53933082e-01],
       [3.91256541e-01, 2.10166402e-01, 1.90672995e-01, 1.58430585e-04,
        4.08031980e-02, 

In [20]:
outp = ReLU.ReLU()
outp.forward([-1,-1,-1,1,1,1])

inp = SoftMax.SoftMax()
inp.forward([[-1,-1,-1,190,1,1]])

array([[1.12138297e-83, 1.12138297e-83, 1.12138297e-83, 1.00000000e+00,
        8.28596168e-83, 8.28596168e-83]])

In [61]:
faux_data_matrix =  np.random.randn(4, 5)
sft_mx = SoftMax()
print(sft_mx.forward(faux_data_matrix)[[0,1,2,3], [0,0,0,0]])
print(sft_mx.forward(faux_data_matrix))

[0.06484056 0.05385979 0.21175089 0.00852724]
[[0.06484056 0.68007258 0.08796346 0.09690622 0.07021718]
 [0.05385979 0.19240152 0.08537821 0.14138571 0.52697477]
 [0.21175089 0.58970521 0.00924564 0.09109485 0.09820341]
 [0.00852724 0.21931281 0.07069741 0.23087648 0.47058606]]


In [66]:
# Code Structure

# Module: Activation Functions

# Module: Neural Networks
# nn_layer
#   function backwards
#   --> inputs are (loss matrix, i.e. gradient for each neuron)
#   --> gradient of loss function d/dx activ_func(x)
#   --> update weight x_i = d/dx_i activ_func(x) for each weight in a neuron
#   --> 

# nn_full_simple
# figure out how to numerical differentiation

1